---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ontap, bluexp, system manager' 
summary: Erfahren Sie, welche neuen BlueXP -Warnmeldungen es gibt. 
---
= Neuerungen bei BlueXP -Warnmeldungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, welche neuen BlueXP -Warnmeldungen es gibt.



== 7 Oktober 2024



=== Seite mit der BlueXP -Meldungsliste

ONTAP-Cluster mit geringer Kapazität oder niedriger Performance lassen sich schnell identifizieren, Verfügbarkeitsgrenzen überprüfen und Sicherheitsrisiken identifizieren. Sie können Warnmeldungen zu Kapazität, Performance, Sicherung, Verfügbarkeit, Sicherheit und Konfiguration anzeigen.



=== Alarmdetails

Sie können Details zu Warnmeldungen anzeigen und Empfehlungen finden.



=== Zeigen Sie mit dem ONTAP System Manager verknüpfte Cluster-Details an

Dank BlueXP -Warnmeldungen lassen sich Warnmeldungen zu Ihrer ONTAP Storage-Umgebung anzeigen sowie Details anzeigen, die mit ONTAP System Manager verknüpft sind.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Informieren Sie sich über BlueXP -Warnmeldungen"].
